swagger: '2.0'
info:
  title: 'Driver List API'
  description: 'API for retrieving a list of driver codes and names'
  version: '1.0.0'
paths:
  /report/drivers/:
    get:
      summary: 'Get a list of driver codes and names'
      parameters:
        - name: order
          in: query
          type: string
          description: 'Sorting order (asc/desc)'
        - name: format
          in: query
          type: string
          description: 'Response format (json/xml)'
      responses:
        200:
          description: 'Successful response'
          schema:
            type: object
            properties:
              response:
                type: object
        400:
          description: 'Bad Request'
          schema:
            type: object
            properties:
              error:
                type: string

