swagger: '2.0'
info:
  title: 'Driver Detail API'
  description: 'API for retrieving information about a specific driver'
  version: '1.0.0'
paths:
  /report/drivers/{driver_slug}:
    get:
      summary: 'Get information about a specific driver'
      parameters:
        - name: driver_slug
          in: path
          type: string
          required: true
          description: 'The ID of the driver'
        - name: format
          in: query
          type: string
          description: 'Response format (json/xml)'
      responses:
        200:
          description: 'Successful response'
          schema:
            type: object
            properties:
              response:
                type: object
        400:
          description: 'Bad Request'
          schema:
            type: object
            properties:
              error:
                type: string
